project:
  type: website
  output-dir: docs

website:
  favicon: img/s4ln-logo.png
  navbar:
    logo: img/s4ln-logo.png
    left:
      - href: index.qmd
        text: Home
      - href: conference.qmd
        text: SMILR

format:
  html:
    theme: pulse
    css: styles.css
    toc: true

filters:
  - googlefonts
googlefonts: ["Londrina Solid"]

