project:
  type: website
  output-dir: docs

website:
  title: "Statistics for Linguistics"
  navbar:
    left:
      - href: index.qmd
        text: Home
      - href: members.qmd
        text: Members list

format:
  html:
    theme: cosmo
    css: styles.css
    toc: true



