---
title: "Statistics for Linguistics"
---

The aim of the **Statistics for Linguistics** Network is to bring together researchers and students in linguistics with an interest in developing and/or disseminating state-of-the-art statistical methods and open research/scholarship practices.

In this initial phase, the objective is to create a **space for knowledge exchange and sharing of resources**. Behind this objective, there is the wish to allow us to learn about each other and to learn from each other.

Future phases will possibly include dedicated events, such as focus groups or conferences on best statistical practices and/or teaching methods for researchers and students in linguistics.

Check the members list [here](members.qmd).

## GitHub Organisation

All communication will happen through the GitHub Organisation Discussions [S4NL](https://github.com/orgs/S4LN/discussions), available to members.

## Join us!

To join the network, please fill in [this form](https://forms.gle/yuK4oEbXy6scn3Ye7).

By submitting this form you agree to your name, institution, linguistics specialisation and statistics experience/expertise being publicly listed on the S4L Network members list. Your email will not be shared.

For more info, get in touch with Ste Coretta at s.coretta *at* ed.ac.uk.